"""user model v2

Revision ID: 6a6f919d7ea7
Revises: 5b704539c815
Create Date: 2025-04-11 19:05:30.912479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a6f919d7ea7"
down_revision: Union[str, None] = "5b704539c815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tbl_users", sa.Column("registerd", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tbl_users", "registerd")
    # ### end Alembic commands ###
